apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app-nginx
        image: cr.yandex/crpasim1ibnrr04p09uq/app-nginx:latest
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: yancr
---

apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      nodePort: 30080
